//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.23 at 02:07:47 PM CEST 
//


package com.csvConvert.company.extractcardrenewalcounter.xml;

import com.csvConvert.company.extractcardrenewalcounter.Artworks;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CardStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardCountPerCardStyle" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{}Artworks" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardStyle",
    "cardCountPerCardStyle",
    "artworks"
})
@XmlRootElement(name = "CardStyle")
public class CardStyle {

    @XmlElement(name = "CardStyle", required = true)
    protected String cardStyle;
    @XmlElement(name = "CardCountPerCardStyle", required = true)
    protected BigInteger cardCountPerCardStyle;
    @XmlElement(name = "Artworks")
    protected Artworks artworks;

    /**
     * Gets the value of the cardStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardStyle() {
        return cardStyle;
    }

    /**
     * Sets the value of the cardStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardStyle(String value) {
        this.cardStyle = value;
    }

    /**
     * Gets the value of the cardCountPerCardStyle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardCountPerCardStyle() {
        return cardCountPerCardStyle;
    }

    /**
     * Sets the value of the cardCountPerCardStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardCountPerCardStyle(BigInteger value) {
        this.cardCountPerCardStyle = value;
    }

    /**
     * Gets the value of the artworks property.
     * 
     * @return
     *     possible object is
     *     {@link Artworks }
     *     
     */
    public Artworks getArtworks() {
        return artworks;
    }

    /**
     * Sets the value of the artworks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Artworks }
     *     
     */
    public void setArtworks(Artworks value) {
        this.artworks = value;
    }

}
