//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.23 at 02:07:47 PM CEST 
//


package com.csvConvert.company.extractcardrenewalcounter;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArtworkCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardCountPerArtworkCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "artworkCode",
    "cardCountPerArtworkCode"
})
@XmlRootElement(name = "Artwork")
public class Artwork {

    @XmlElement(name = "ArtworkCode", required = true)
    protected String artworkCode;
    @XmlElement(name = "CardCountPerArtworkCode", required = true)
    protected BigInteger cardCountPerArtworkCode;

    /**
     * Gets the value of the artworkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtworkCode() {
        return artworkCode;
    }

    /**
     * Sets the value of the artworkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtworkCode(String value) {
        this.artworkCode = value;
    }

    /**
     * Gets the value of the cardCountPerArtworkCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardCountPerArtworkCode() {
        return cardCountPerArtworkCode;
    }

    /**
     * Sets the value of the cardCountPerArtworkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardCountPerArtworkCode(BigInteger value) {
        this.cardCountPerArtworkCode = value;
    }

}
